name: avro
version: '0.4.1.1'
synopsis: Avro serialization support for Haskell
description: Avro serialization and deserialization support for Haskell
category: Data
author: Thomas M. DuBuisson
maintainer: Alexey Raga <alexey.raga@gmail.com>
license: BSD3
github: GaloisInc/avro
extra-source-files:
- README.md
- ChangeLog.md
- test/data/*.avsc
- test/data/*.json
- test/data/*/*.avsc
dependencies:
- aeson
- array
- base16-bytestring
- bifunctors
- binary
- bytestring
- containers
- fail
- hashable
- mtl
- pure-zlib
- scientific
- semigroups
- tagged
- text
- tf-random
- unordered-containers
- vector
library:
  source-dirs: src
  other-extensions:
  - OverloadedStrings
  ghc-options: -O2
  dependencies:
  - base >=4.8 && <5.0
  - data-binary-ieee754
  when:
  - condition: flag(templatehaskell)
    other-extensions:
    - TemplateHaskell
    dependencies:
    - template-haskell >=2.4
  - condition: flag(dev)
    ghc-options:
    - -Wall
    - -Werror
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded
    dependencies:
    - base >=4.6 && <5
    - lens-aeson
    - avro
    - directory
    - extra
    - hspec
    - lens
    - QuickCheck
    - transformers
    when:
    - condition: flag(templatehaskell)
      other-extensions:
      - TemplateHaskell
      dependencies:
      - template-haskell
    - condition: flag(dev)
      ghc-options:
      - -Wall
      - -Werror
flags:
  templatehaskell:
    description: Build Avro.Deriving, which uses Template Haskell.
    manual: false
    default: true
  dev:
    description: Use development GHC flags
    manual: true
    default: false
